name: math_expression_parser
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.6.14
  google_fonts: ^5.0.0
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.13.1

# run 'flutter pub run flutter_launcher_icons' to get the icons
flutter_launcher_icons:
  android: true
  image_path: "assets/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
  # windows:
  #   generate: true
  #   image_path: "assets/icon.png"
  #   icon_size: 48 # min:48, max:256, default: 48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - design_references/
    

