name: math_expression_parser
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.2+6

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^6.0.0
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.13.1
  http: ^1.1.0
  lorem_ipsum: ^0.0.3
  shared_preferences: ^2.2.0
  flutter_markdown: ^0.7.1

# run 'flutter pub run flutter_launcher_icons' to get the icons
flutter_launcher_icons:
  android: true
  image_path: "assets/math parser logob.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/math parser logob.png"
  # windows:
  #   generate: true
  #   image_path: "assets/icon.png"
  #   icon_size: 48 # min:48, max:256, default: 48

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/markdown/
    - screenshots/
    - screenshots/edited/all_dark.jpg
    - README.md
    

